spring:
  application:
    name: votessystem
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example

server:
  port: 8080

votessystem:
    associatedvotestatus:
      url: https://user-info.herokuapp.com/users/
      votestatus: "/{cpf}"