spring:
  application:
    name: votessystem
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

server:
  port: 8080

votessystem:
    associatedvotestatus:
      url: https://user-info.herokuapp.com/users/
      votestatus: "/{cpf}"