CREATE TABLE VOTO(
	VOTE_ID INTEGER NOT NULL,
	PAUTA_ID INTEGER NOT NULL,
	ASSOCIATED_ID INTEGER,
	VOTE BOOLEAN NOT NULL,
	FOREIGN KEY(PAUTA_ID) REFERENCES PAUTA (PAUTA_ID),
	FOREIGN KEY(ASSOCIATED_ID) REFERENCES ASSOCIATED (ASSOCIATED_ID),
    PRIMARY KEY (VOTE_ID)
)
